// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPagination.Data;

namespace WebApiPagination.Data.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    [Migration("20210901211824_SeedTeamTable")]
    partial class SeedTeamTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiPagination.Entities.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WebApiPagination.Entities.Models.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1610610023L,
                            City = "Packers",
                            Name = "Anderson",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610024L,
                            City = "Bullets",
                            Name = "Baltimore",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610025L,
                            City = "Stags",
                            Name = "Chicago",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610026L,
                            City = "Rebels",
                            Name = "Cleveland",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610027L,
                            City = "Nuggets",
                            Name = "Denver",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610028L,
                            City = "Falcons",
                            Name = "Detroit",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610029L,
                            City = "Jets",
                            Name = "Indianapolis",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610030L,
                            City = "Olympians",
                            Name = "Indianapolis",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610031L,
                            City = "Ironmen",
                            Name = "Pittsburgh",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610032L,
                            City = "Steamrollers",
                            Name = "Providence",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610033L,
                            City = "Redskins",
                            Name = "Sheboygan",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610034L,
                            City = "Bombers",
                            Name = "St. Louis",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610035L,
                            City = "Huskies",
                            Name = "Toronto",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610036L,
                            City = "Capitols",
                            Name = "Washington",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610610037L,
                            City = "Hawks",
                            Name = "Waterloo",
                            Slug = ""
                        },
                        new
                        {
                            Id = 1610612737L,
                            City = "Hawks",
                            Name = "Atlanta",
                            Slug = "hawks"
                        },
                        new
                        {
                            Id = 1610612738L,
                            City = "Celtics",
                            Name = "Boston",
                            Slug = "celtics"
                        },
                        new
                        {
                            Id = 1610612739L,
                            City = "Cavaliers",
                            Name = "Cleveland",
                            Slug = "cavaliers"
                        },
                        new
                        {
                            Id = 1610612740L,
                            City = "Pelicans",
                            Name = "New Orleans",
                            Slug = "pelicans"
                        },
                        new
                        {
                            Id = 1610612741L,
                            City = "Bulls",
                            Name = "Chicago",
                            Slug = "bulls"
                        },
                        new
                        {
                            Id = 1610612742L,
                            City = "Mavericks",
                            Name = "Dallas",
                            Slug = "mavericks"
                        },
                        new
                        {
                            Id = 1610612743L,
                            City = "Nuggets",
                            Name = "Denver",
                            Slug = "nuggets"
                        },
                        new
                        {
                            Id = 1610612744L,
                            City = "Warriors",
                            Name = "Golden State",
                            Slug = "warriors"
                        },
                        new
                        {
                            Id = 1610612745L,
                            City = "Rockets",
                            Name = "Houston",
                            Slug = "rockets"
                        },
                        new
                        {
                            Id = 1610612746L,
                            City = "Clippers",
                            Name = "LA",
                            Slug = "clippers"
                        },
                        new
                        {
                            Id = 1610612747L,
                            City = "Lakers",
                            Name = "Los Angeles",
                            Slug = "lakers"
                        },
                        new
                        {
                            Id = 1610612748L,
                            City = "Heat",
                            Name = "Miami",
                            Slug = "heat"
                        },
                        new
                        {
                            Id = 1610612749L,
                            City = "Bucks",
                            Name = "Milwaukee",
                            Slug = "bucks"
                        },
                        new
                        {
                            Id = 1610612750L,
                            City = "Timberwolves",
                            Name = "Minnesota",
                            Slug = "timberwolves"
                        },
                        new
                        {
                            Id = 1610612751L,
                            City = "Nets",
                            Name = "Brooklyn",
                            Slug = "nets"
                        },
                        new
                        {
                            Id = 1610612752L,
                            City = "Knicks",
                            Name = "New York",
                            Slug = "knicks"
                        },
                        new
                        {
                            Id = 1610612753L,
                            City = "Magic",
                            Name = "Orlando",
                            Slug = "magic"
                        },
                        new
                        {
                            Id = 1610612754L,
                            City = "Pacers",
                            Name = "Indiana",
                            Slug = "pacers"
                        },
                        new
                        {
                            Id = 1610612755L,
                            City = "76ers",
                            Name = "Philadelphia",
                            Slug = "sixers"
                        },
                        new
                        {
                            Id = 1610612756L,
                            City = "Suns",
                            Name = "Phoenix",
                            Slug = "suns"
                        },
                        new
                        {
                            Id = 1610612757L,
                            City = "Trail Blazers",
                            Name = "Portland",
                            Slug = "blazers"
                        },
                        new
                        {
                            Id = 1610612758L,
                            City = "Kings",
                            Name = "Sacramento",
                            Slug = "kings"
                        },
                        new
                        {
                            Id = 1610612759L,
                            City = "Spurs",
                            Name = "San Antonio",
                            Slug = "spurs"
                        },
                        new
                        {
                            Id = 1610612760L,
                            City = "Thunder",
                            Name = "Oklahoma City",
                            Slug = "thunder"
                        },
                        new
                        {
                            Id = 1610612761L,
                            City = "Raptors",
                            Name = "Toronto",
                            Slug = "raptors"
                        },
                        new
                        {
                            Id = 1610612762L,
                            City = "Jazz",
                            Name = "Utah",
                            Slug = "jazz"
                        },
                        new
                        {
                            Id = 1610612763L,
                            City = "Grizzlies",
                            Name = "Memphis",
                            Slug = "grizzlies"
                        },
                        new
                        {
                            Id = 1610612764L,
                            City = "Wizards",
                            Name = "Washington",
                            Slug = "wizards"
                        },
                        new
                        {
                            Id = 1610612765L,
                            City = "Pistons",
                            Name = "Detroit",
                            Slug = "pistons"
                        },
                        new
                        {
                            Id = 1610612766L,
                            City = "Hornets",
                            Name = "Charlotte",
                            Slug = "hornets"
                        });
                });

            modelBuilder.Entity("WebApiPagination.Entities.Models.Player", b =>
                {
                    b.HasOne("WebApiPagination.Entities.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WebApiPagination.Entities.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
